main: me.tommycake50.stuckinthemud.StuckInTheMud
author: tommycake50
version: 1
name: CentralStuckInTheMud
commands:
    stuck:
        usage: /stuck start, starts a game of stuck
        description: stuck command
